production:
  cloud_name: "e-shop"

  api_key: <%= Rails.application.secrets[:cloudinary_api_key] || ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= Rails.application.secrets[:cloudinary_api_secret] || ENV['CLOUDINARY_API_SECRET'] %>

  enhance_image_tag: true
  static_image_support: true

development:
  cloud_name: "e-shop"

  api_key: <%= Rails.application.secrets[:cloudinary_api_key] || ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= Rails.application.secrets[:cloudinary_api_secret] || ENV['CLOUDINARY_API_SECRET'] %>

  enhance_image_tag: true
  static_image_support: true
