development:
  mandrill_username:
  mandrill_apikey:
  cloudinary_api_key:
  cloudinary_api_secret:
  secret_key_base: e22fe6436e8b1949922d982ed6333f5cd345556c08eba7cf7dee6f4ede55307be301fc6630bdecc1b632f1217929a846137116fb872925456c5df9d8d315f9c2

production:
  secret_key_base: e22fe6436e8b1949922d982ed6333f5cd345556c08eba7cf7dee6f4ede55307be301fc6630bdecc1b632f1217929a846137116fb872925456c5df9d8d315f9c2

test:
  secret_key_base: e22fe6436e8b1949922d982ed6333f5cd345556c08eba7cf7dee6f4ede55307be301fc6630bdecc1b632f1217929a846137116fb872925456c5df9d8d315f9c2



